# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#trigger:
#- master
variables:
- name: ALMOctaneLogLevel
  value: DEBUG

jobs:
- job: MavenBuildJob
  pool: 'Default'
  dependsOn:
  - AlmOctaneStartJob
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
- job: AlmOctaneStartJob
  condition: always()
  pool: 'Default'
  steps:
  - task: octane-start-task@2
    inputs:
      OctaneServiceConnection: 'MyLocalOctaneService'
      WorkspaceList: '1002'
      GithubRepositoryConnection: 'azure_git_hub'
      CreatePipelineCheckbox: true
- job: AlmOctaneEndJob
  condition: always()
  pool: 'Default'
  dependsOn:
  - AlmOctaneStartJob
  - MavenBuildJob
  steps:
  - task: octane-end-task@2
    inputs:
      OctaneServiceConnection: 'MyLocalOctaneService'
      WorkspaceList: '1002'
      GithubRepositoryConnection: 'azure_git_hub'
- job: AlmOctaneStartJobPrivate
  condition: false
  pool: 'Default'
  steps:
  - task: octane-start-task-private@1
    inputs:
      OctaneServiceConnection: 'ALMOctanePrivateNightlyDev'
      WorkspaceList: '1002'
      GithubRepositoryConnection: 'azure_git_hub'
- job: AlmOctaneEndJobPrivate
  condition: false
  pool: 'Default'
  dependsOn:
  - AlmOctaneStartJobPrivate
  - MavenBuildJob
  steps:
  - task: octane-end-task-private@1
    inputs:
      OctaneServiceConnection: 'ALMOctanePrivateNightlyDev'
      WorkspaceList: '1002'
      GithubRepositoryConnection: 'azure_git_hub'